### ISSUE TITLE
Error while calling zoomIn/zoomOut/resetTransform

### ISSUE THREAD

**Issue by olaf89** [prc5/react-zoom-pan-pinch#67]
Sometimes when using zoomIn/zoomOut/resetTransform app crashes. Noticed it when updating version 1.4.5 to 1.5.5

TypeError: Failed to execute 'requestAnimationFrame' on 'Window': The callback provided as parameter 1 is not a function.

```
  this.animation = () => {
    if (!this.animation || !this.mounted) return;
    const frameTime = new Date().getTime() - startTime;
    const animationProgress = frameTime / animationTime;
    const animationType = availableAnimations[animationName];

    const step = animationType(animationProgress);

    if (frameTime >= animationTime) {
      callback(lastStep);
      this.animation = null;
    } else {
      callback(step);
      requestAnimationFrame(this.animation); << CRASHES HERE
    }
  };
```

**Comment by prc5** [comment]
Can you give me more detail? When this is happening?

**Comment by zpetukhov** [comment]
@prc5 
Faced with the same error.
I have replaced the line which is marked "<< CRASHES HERE" to the following:
```
      const savedAnimation = this.animation;
      callback(step);
      if (this.animation) {
        requestAnimationFrame(this.animation);
      } else {
        console.error('requestAnimationFrame Error here', this.animation, savedAnimation);
      }
```
this prevents the error and throws the following to console:
index.js:2178 requestAnimationFrame Error here null ƒ () {

So, it looks like the callback call nullifies the 'this.animation'.

> Can you give me more detail? When this is happening?

I started to test the lib. I like it. But there are a couple of issues.
My first tries are zoom/pan single IMG tag.
Details of my test (when the error happening):
viewport size: 1920x723
image size:1920x1080
scale: 1
How to reproduce? Simply do double click after the app loads.
This constantly throws the error.
So please fix it :)

Another issue: double click changes the scale a way too little.
Yes I saw your 'example' app and double click works pretty well there.
But it works not as expected with my viewport / image sizes.
It changes from 1 to 1.0049862220589691 (this value differs and probably depends on click coordinates, but it always like that - from 1.004 to 1.007).
Changing 'options.wheel.step' not seem to have any effect
(as described in the issue 83 https://github.com/prc5/react-zoom-pan-pinch/issues/83)

I'm not an expert in JS development yet - started to learn it not a long time ago - so I can't provide any fixes / pull requests, sorry.
